# Copyright 2016 ParanoidAndroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/htc/flounder/proprietary/system/etc/fmas_eq.dat:$(TARGET_COPY_OUT_SYSTEM)/etc/fmas_eq.dat:htc \
    vendor/htc/flounder/proprietary/system/etc/RT5506:$(TARGET_COPY_OUT_SYSTEM)/etc/RT5506:htc \
    vendor/htc/flounder/proprietary/system/lib/soundfx/libfmas.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libfmas.so:htc \
    vendor/htc/flounder/proprietary/vendor/bin/tegrastats:$(TARGET_COPY_OUT_VENDOR)/bin/tegrastats:htc \
    vendor/htc/flounder/proprietary/vendor/bin/tlk_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/tlk_daemon:htc \
    vendor/htc/flounder/proprietary/vendor/bin/touch_fusion:$(TARGET_COPY_OUT_VENDOR)/bin/touch_fusion:htc \
    vendor/htc/flounder/proprietary/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf:htc \
    vendor/htc/flounder/proprietary/vendor/etc/model_frontal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/model_frontal.xml:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/LVVEFS_Rx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/LVVEFS_Rx_Configuration.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/LVVEFS_Tx_Configuration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/LVVEFS_Tx_Configuration.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_EARPIECE_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_SPEAKER_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Rx_ControlParams_WIRED_HEADSET_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_CARKIT_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_BLUETOOTH_SCO_HEADSET_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_EARPIECE_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_SPEAKER_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADPHONE_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_16000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_24000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_32000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_48000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Tx_ControlParams_WIRED_HEADSET_8000Hz.txt:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback_l.preset:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.config:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG_l.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.config:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG_l.preset:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playbackMFG.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playbackMFG.preset:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/playback.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/playback.preset:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/tfa9895.config:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.config:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/tfa9895_l.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895_l.speaker:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/tfa9895MFG.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895MFG.patch:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/tfa9895.patch:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.patch:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/tfa9895.speaker:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/tfa9895.speaker:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip_l.drc:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.drc:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip_l.eq:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.eq:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip_l.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip_l.preset:htc \
    vendor/htc/flounder/proprietary/vendor/etc/tfa/voip.preset:$(TARGET_COPY_OUT_VENDOR)/etc/tfa/voip.preset:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/bcm20795_firmware.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm20795_firmware.ncd:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/bcm4350b1.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350b1.hcd:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/bcm4350c0.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350c0.hcd:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/bcm4354.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4354.hcd:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd_apsta.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/fw_bcmdhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fw_bcmdhd.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/maxim_fp35.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/maxim_fp35.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_aacdec_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_aacdec_ucode.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_aud_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_aud_ucode.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_mp3dec_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_mp3dec_ucode.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_os_0ff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_0ff00000.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_os_8ff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_8ff00000.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_os_eff00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_eff00000.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_os_f7e00000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_os_f7e00000.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/nvavp_vid_ucode_alt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvavp_vid_ucode_alt.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/rt5677_elf_vad:$(TARGET_COPY_OUT_VENDOR)/firmware/rt5677_elf_vad:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/sar0_CY8C.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sar0_CY8C.img:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/sar1_CY8C.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sar1_CY8C.img:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/sensor_hub.img:$(TARGET_COPY_OUT_VENDOR)/firmware/sensor_hub.img:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/synaptics.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics.img:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/fecs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/fecs.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/gpccs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/gpccs.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/gpmu_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/gpmu_ucode.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/NETB_img.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/NETB_img.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/nvhost_msenc031.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/nvhost_msenc031.fw:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/nvhost_tsec.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/nvhost_tsec.fw:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/tegra13x/vic03_ucode.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tegra13x/vic03_ucode.bin:htc \
    vendor/htc/flounder/proprietary/vendor/firmware/touch_fusion.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_fusion.cfg:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/egl/libEGL_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/egl/libGLESv1_CM_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/egl/libGLESv2_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/gatekeeper.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.flounder.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/gralloc.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/hwcomposer.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/keystore.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.flounder.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/hw/memtrack.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libclcore_nvidia.bc:$(TARGET_COPY_OUT_VENDOR)/lib64/libclcore_nvidia.bc:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfrsdk.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libglcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libglcore.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libhtcacoustic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhtcacoustic.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvapputil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvapputil.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvblit.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvblit.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvcms.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvcms.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvcompute.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvcompute.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvddk_2d_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvddk_2d_v2.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvddk_vic.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvddk_vic.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvglsi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvglsi.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvgr.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvos.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvos.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvptx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvptx.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvrmapi_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrmapi_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvrm_graphics.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm_graphics.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvrm.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvRSCompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvRSCompiler.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvRSDriver.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvRSDriver.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libnvwsi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvwsi.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libdrmclearkeyplugin.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/egl/libEGL_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/egl/libGLESv1_CM_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/egl/libGLESv2_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/camera.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/gatekeeper.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.flounder.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/gralloc.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/hwcomposer.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/keystore.flounder.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.flounder.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/hw/memtrack.tegra132.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.tegra132.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libaudioavp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioavp.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libclcore_nvidia.bc:$(TARGET_COPY_OUT_VENDOR)/lib/libclcore_nvidia.bc:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfrsdk.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libglcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libglcore.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libhtcacoustic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhtcacoustic.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libLifevibes_lvverx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLifevibes_lvverx.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libLifevibes_lvvetx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libLifevibes_lvvetx.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvapputil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvapputil.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvavp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvavp.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvblit.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvblit.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvcamerahdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcamerahdr.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvcam_imageencoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcam_imageencoder.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvcapclk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcapclk.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvcms.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcms.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvcompute.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvcompute.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvddk_2d.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_2d.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvddk_2d_v2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_2d_v2.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvddk_vic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvddk_vic.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvfusebypass.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvfusebypass.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvglsi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvglsi.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvgr.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvisp_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvisp_v3.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_audio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_audio.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_camera_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_camera_v3.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_contentpipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_contentpipe.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmmlite_audio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_audio.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmmlite_image.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_image.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmmlite.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmmlite_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_utils.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmmlite_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmmlite_video.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_parser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_parser.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_utils.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvmm_writer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvmm_writer.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvodm_imager.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvodm_imager.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvodm_query.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvodm_query.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvomxilclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvomxilclient.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvomx.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvos.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvos.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvparser.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvptx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvptx.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvrmapi_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrmapi_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvrm_graphics.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrm_graphics.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvrm.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvRSCompiler.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvRSCompiler.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvRSDriver.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvRSDriver.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvsm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvsm.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvtnr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvtnr.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvtvmr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvtvmr.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvvicsi_v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvvicsi_v3.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libnvwsi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvwsi.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libopencv24_tegra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libopencv24_tegra.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libtsechdcp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtsechdcp.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so:htc \
    vendor/htc/flounder/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so:htc \
    vendor/htc/flounder/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd:htc \
    vendor/htc/flounder/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd:htc \
    vendor/htc/flounder/proprietary/vendor/push_info.txt:$(TARGET_COPY_OUT_VENDOR)/push_info.txt:htc
